version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app_be:
    build: .
    container_name: telemedicina_be
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TZ: America/Guayaquil
    ports:
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgres_data:
    external: true
    name: telemedicinabe_postgres_data
